export const immobili = [
  {
    immagine: "https://example.com/immagine1.jpg",
    prezzo: 250000 + "€",
    via: "Via Roma 10, Milano",
    tipologie_di_casa: "Appartamento",
    camere_da_letto: 3,
    bagni: 2,
    parcheggio: "no",
  },
  {
    immagine: "https://example.com/immagine2.jpg",
    prezzo: 320000 + "€",
    via: "Via Milano 22, Roma",
    tipologie_di_casa: "Villa",
    camere_da_letto: 4,
    bagni: 3,
    parcheggio: "si",
  },
  {
    immagine: "https://example.com/immagine3.jpg",
    prezzo: 180000 + "€",
    via: "Via Torino 5, Torino",
    tipologie_di_casa: "Appartamento",
    camere_da_letto: 2,
    bagni: 1,
    parcheggio: "no",
  },
  {
    immagine: "https://example.com/immagine4.jpg",
    prezzo: 450000 + "€",
    via: "Via Napoli 18, Napoli",
    tipologie_di_casa: "Attico",
    camere_da_letto: 5,
    bagni: 4,
    parcheggio: "si",
  },
  {
    immagine: "https://example.com/immagine5.jpg",
    prezzo: 280000 + "€",
    via: "Via Genova 3, Genova",
    tipologie_di_casa: "Appartamento",
    camere_da_letto: 3,
    bagni: 2,
    parcheggio: "si",
  },
];
